---
resources:
- name: nanoservices
  type: git
  source:
    uri: https://github.com/wellingtonxxl/nanoservices-serverless
    branch: main

jobs:
  - name: builderman
    public: true
    plan:
      - get: nanoservices
      - task: run tests
        file: nanoservices/source/ci/tasks/run_tests.yml